### ISSUE TITLE
How to generate sitemap based on dynamic routes?

### ISSUE THREAD

**Issue by kaloraat** [IlusionDev/nextjs-sitemap-generator#12]
First of all thanks for great package. It works perfectly with static pages. But does it work for dynamically generated pages? For dynamic page, I am getting something like this:

`<loc>https://domain.com.au/tags/[slug]/index</loc>`

Based on tags/slug the pages will be different. How would I be able to generate such sitemap any ideas? I have separate api and separate next client. Thanks!

**Comment by IlusionDev** [comment]
Hi, the quick answer is you can't. You need to know the existing pages to generate it's map.
In the case of generate a page in runing time you should map again and that can cause a performance problem.

An option is, if you can know the posibly pages, for example the slug is an id that referes something in a db. In that case you can generate a file like ( [ID].js ) for each entry and the sitemap-generator will generate a page with the name of ( [ID].js ).

But I not recomend do that because you going to cause a performance problem on each new page.

**Comment by schrapel** [comment]
@IlusionDev Would you be open to the idea of a feature like the below. When you prepare to generate a sitemap entry that has a dynamic entry you can check to see if there is a way to retrieve those values from the config option. The getServices function could be a axios request that returns a response. 

```
const getServices = async () => {
  // return ...
}

sitemap({  
  dynamicPaths: {
    '/services/[service]/[subservice]': await getServices()
  } 
});
```

**Comment by IlusionDev** [comment]
Excelent idea, of course you can make a PR.
I can't wait to see that.

**Comment by jlaramie** [comment]
Without noticing this issue I implemented a similar feature by using exportPathmap https://github.com/IlusionDev/nextjs-sitemap-generator/pull/13
